		hdr.http_url[0].setValid();
		hdr.http_url[0].ch = 0;
		hdr.http_url[0].setInvalid();
		hdr.http_url[1].setValid();
		hdr.http_url[1].ch = 0;
		hdr.http_url[1].setInvalid();
		hdr.http_url[2].setValid();
		hdr.http_url[2].ch = 0;
		hdr.http_url[2].setInvalid();
		hdr.http_url[3].setValid();
		hdr.http_url[3].ch = 0;
		hdr.http_url[3].setInvalid();
		hdr.http_url[4].setValid();
		hdr.http_url[4].ch = 0;
		hdr.http_url[4].setInvalid();
		hdr.http_url[5].setValid();
		hdr.http_url[5].ch = 0;
		hdr.http_url[5].setInvalid();
		hdr.http_url[6].setValid();
		hdr.http_url[6].ch = 0;
		hdr.http_url[6].setInvalid();
		hdr.http_url[7].setValid();
		hdr.http_url[7].ch = 0;
		hdr.http_url[7].setInvalid();
		hdr.http_url[8].setValid();
		hdr.http_url[8].ch = 0;
		hdr.http_url[8].setInvalid();
		hdr.http_url[9].setValid();
		hdr.http_url[9].ch = 0;
		hdr.http_url[9].setInvalid();
		hdr.http_url[10].setValid();
		hdr.http_url[10].ch = 0;
		hdr.http_url[10].setInvalid();
		hdr.http_url[11].setValid();
		hdr.http_url[11].ch = 0;
		hdr.http_url[11].setInvalid();
		hdr.http_url[12].setValid();
		hdr.http_url[12].ch = 0;
		hdr.http_url[12].setInvalid();
		hdr.http_url[13].setValid();
		hdr.http_url[13].ch = 0;
		hdr.http_url[13].setInvalid();
		hdr.http_url[14].setValid();
		hdr.http_url[14].ch = 0;
		hdr.http_url[14].setInvalid();
		hdr.http_url[15].setValid();
		hdr.http_url[15].ch = 0;
		hdr.http_url[15].setInvalid();
		hdr.http_url[16].setValid();
		hdr.http_url[16].ch = 0;
		hdr.http_url[16].setInvalid();
		hdr.http_url[17].setValid();
		hdr.http_url[17].ch = 0;
		hdr.http_url[17].setInvalid();
		hdr.http_url[18].setValid();
		hdr.http_url[18].ch = 0;
		hdr.http_url[18].setInvalid();
		hdr.http_url[19].setValid();
		hdr.http_url[19].ch = 0;
		hdr.http_url[19].setInvalid();
		hdr.http_url[20].setValid();
		hdr.http_url[20].ch = 0;
		hdr.http_url[20].setInvalid();
		hdr.http_url[21].setValid();
		hdr.http_url[21].ch = 0;
		hdr.http_url[21].setInvalid();
		hdr.http_url[22].setValid();
		hdr.http_url[22].ch = 0;
		hdr.http_url[22].setInvalid();
		hdr.http_url[23].setValid();
		hdr.http_url[23].ch = 0;
		hdr.http_url[23].setInvalid();
		hdr.http_url[24].setValid();
		hdr.http_url[24].ch = 0;
		hdr.http_url[24].setInvalid();
		hdr.http_url[25].setValid();
		hdr.http_url[25].ch = 0;
		hdr.http_url[25].setInvalid();
		hdr.http_url[26].setValid();
		hdr.http_url[26].ch = 0;
		hdr.http_url[26].setInvalid();
		hdr.http_url[27].setValid();
		hdr.http_url[27].ch = 0;
		hdr.http_url[27].setInvalid();
		hdr.http_url[28].setValid();
		hdr.http_url[28].ch = 0;
		hdr.http_url[28].setInvalid();
		hdr.http_url[29].setValid();
		hdr.http_url[29].ch = 0;
		hdr.http_url[29].setInvalid();
		hdr.http_url[30].setValid();
		hdr.http_url[30].ch = 0;
		hdr.http_url[30].setInvalid();
		hdr.http_url[31].setValid();
		hdr.http_url[31].ch = 0;
		hdr.http_url[31].setInvalid();
